# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keyboard_record.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_keyboard_recorder(object):
    def setupUi(self, keyboard_recorder):
        keyboard_recorder.setObjectName("keyboard_recorder")
        keyboard_recorder.resize(274, 259)
        keyboard_recorder.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(keyboard_recorder)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_main = QtWidgets.QFrame(keyboard_recorder)
        self.frame_main.setMinimumSize(QtCore.QSize(270, 250))
        self.frame_main.setStyleSheet("")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_op = QtWidgets.QLabel(self.frame_main)
        self.lbl_op.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_op.setFont(font)
        self.lbl_op.setStyleSheet("")
        self.lbl_op.setLineWidth(0)
        self.lbl_op.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_op.setWordWrap(True)
        self.lbl_op.setObjectName("lbl_op")
        self.verticalLayout.addWidget(self.lbl_op)
        self.lbl_info = QtWidgets.QLabel(self.frame_main)
        self.lbl_info.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lbl_info.setFont(font)
        self.lbl_info.setStyleSheet("")
        self.lbl_info.setObjectName("lbl_info")
        self.verticalLayout.addWidget(self.lbl_info)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout_2.addWidget(self.frame_main)

        self.retranslateUi(keyboard_recorder)
        QtCore.QMetaObject.connectSlotsByName(keyboard_recorder)

    def retranslateUi(self, keyboard_recorder):
        _translate = QtCore.QCoreApplication.translate
        keyboard_recorder.setWindowTitle(_translate("keyboard_recorder", "Form"))
        self.lbl_op.setText(_translate("keyboard_recorder", "显示键盘录制的按键"))
        self.lbl_info.setText(_translate("keyboard_recorder", "Tab + Esc: 退出"))
