# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'position_xy.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(320, 48)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        Form.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pos_x_spinBox = QtWidgets.QSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_x_spinBox.sizePolicy().hasHeightForWidth())
        self.pos_x_spinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.pos_x_spinBox.setFont(font)
        self.pos_x_spinBox.setWrapping(True)
        self.pos_x_spinBox.setSuffix("")
        self.pos_x_spinBox.setMinimum(-9999)
        self.pos_x_spinBox.setMaximum(9999)
        self.pos_x_spinBox.setObjectName("pos_x_spinBox")
        self.horizontalLayout.addWidget(self.pos_x_spinBox)
        self.pos_y_spinBox = QtWidgets.QSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pos_y_spinBox.sizePolicy().hasHeightForWidth())
        self.pos_y_spinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(9)
        self.pos_y_spinBox.setFont(font)
        self.pos_y_spinBox.setWrapping(True)
        self.pos_y_spinBox.setMinimum(-9999)
        self.pos_y_spinBox.setMaximum(9999)
        self.pos_y_spinBox.setDisplayIntegerBase(10)
        self.pos_y_spinBox.setObjectName("pos_y_spinBox")
        self.horizontalLayout.addWidget(self.pos_y_spinBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pos_x_spinBox.setStatusTip(_translate("Form", "屏幕水平坐标或水平偏移"))
        self.pos_x_spinBox.setPrefix(_translate("Form", "X:"))
        self.pos_y_spinBox.setStatusTip(_translate("Form", "屏幕竖直坐标或竖直偏移"))
        self.pos_y_spinBox.setPrefix(_translate("Form", "Y:"))
